name: CI

on:
  push:
  pull_request:

jobs:
  perl-job:
    runs-on: ubuntu-latest

    container:
      image: perldocker/perl-tester:5.40     # https://hub.docker.com/r/perldocker/perl-tester
    name: Perl
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
            cpanm --quiet --installdeps --verbose --notest .

      - name: Tests
        run: |
            prove

